//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest.ServiceClovek {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClovekResult", Namespace="http://schemas.datacontract.org/2004/07/WcfDb")]
    [System.SerializableAttribute()]
    public partial class ClovekResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebApiTest.ServiceClovek.ClovekContract> ValuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebApiTest.ServiceClovek.ClovekContract> Values {
            get {
                return this.ValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuesField, value) != true)) {
                    this.ValuesField = value;
                    this.RaisePropertyChanged("Values");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClovekContract", Namespace="http://schemas.datacontract.org/2004/07/WcfDb")]
    [System.SerializableAttribute()]
    public partial class ClovekContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JmenoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jmeno {
            get {
                return this.JmenoField;
            }
            set {
                if ((object.ReferenceEquals(this.JmenoField, value) != true)) {
                    this.JmenoField = value;
                    this.RaisePropertyChanged("Jmeno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clovek", Namespace="http://schemas.datacontract.org/2004/07/WcfDb")]
    [System.SerializableAttribute()]
    public partial class Clovek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JmenoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jmeno {
            get {
                return this.JmenoField;
            }
            set {
                if ((object.ReferenceEquals(this.JmenoField, value) != true)) {
                    this.JmenoField = value;
                    this.RaisePropertyChanged("Jmeno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceClovek.IServiceClovek")]
    public interface IServiceClovek {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClovek/GetClovek", ReplyAction="http://tempuri.org/IServiceClovek/GetClovekResponse")]
        WebApiTest.ServiceClovek.ClovekResult GetClovek();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClovek/GetClovek", ReplyAction="http://tempuri.org/IServiceClovek/GetClovekResponse")]
        System.Threading.Tasks.Task<WebApiTest.ServiceClovek.ClovekResult> GetClovekAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClovek/InsertClovek", ReplyAction="http://tempuri.org/IServiceClovek/InsertClovekResponse")]
        void InsertClovek(WebApiTest.ServiceClovek.Clovek clovek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClovek/InsertClovek", ReplyAction="http://tempuri.org/IServiceClovek/InsertClovekResponse")]
        System.Threading.Tasks.Task InsertClovekAsync(WebApiTest.ServiceClovek.Clovek clovek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClovek/UpdateClovek", ReplyAction="http://tempuri.org/IServiceClovek/UpdateClovekResponse")]
        void UpdateClovek(WebApiTest.ServiceClovek.Clovek clovek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClovek/UpdateClovek", ReplyAction="http://tempuri.org/IServiceClovek/UpdateClovekResponse")]
        System.Threading.Tasks.Task UpdateClovekAsync(WebApiTest.ServiceClovek.Clovek clovek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClovek/DeleteClovek", ReplyAction="http://tempuri.org/IServiceClovek/DeleteClovekResponse")]
        void DeleteClovek(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClovek/DeleteClovek", ReplyAction="http://tempuri.org/IServiceClovek/DeleteClovekResponse")]
        System.Threading.Tasks.Task DeleteClovekAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceClovekChannel : WebApiTest.ServiceClovek.IServiceClovek, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClovekClient : System.ServiceModel.ClientBase<WebApiTest.ServiceClovek.IServiceClovek>, WebApiTest.ServiceClovek.IServiceClovek {
        
        public ServiceClovekClient() {
        }
        
        public ServiceClovekClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClovekClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClovekClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClovekClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApiTest.ServiceClovek.ClovekResult GetClovek() {
            return base.Channel.GetClovek();
        }
        
        public System.Threading.Tasks.Task<WebApiTest.ServiceClovek.ClovekResult> GetClovekAsync() {
            return base.Channel.GetClovekAsync();
        }
        
        public void InsertClovek(WebApiTest.ServiceClovek.Clovek clovek) {
            base.Channel.InsertClovek(clovek);
        }
        
        public System.Threading.Tasks.Task InsertClovekAsync(WebApiTest.ServiceClovek.Clovek clovek) {
            return base.Channel.InsertClovekAsync(clovek);
        }
        
        public void UpdateClovek(WebApiTest.ServiceClovek.Clovek clovek) {
            base.Channel.UpdateClovek(clovek);
        }
        
        public System.Threading.Tasks.Task UpdateClovekAsync(WebApiTest.ServiceClovek.Clovek clovek) {
            return base.Channel.UpdateClovekAsync(clovek);
        }
        
        public void DeleteClovek(int Id) {
            base.Channel.DeleteClovek(Id);
        }
        
        public System.Threading.Tasks.Task DeleteClovekAsync(int Id) {
            return base.Channel.DeleteClovekAsync(Id);
        }
    }
}
